### ISSUE TITLE
mesh_plot

### ISSUE THREAD

**Issue by dialuser** [noaa-ocs-modeling/adcircpy#154]
Hi I'm new to adcircpy. I tried to follow example1, but added some mesh plot part,

    # open mesh file
    mesh = AdcircMesh.open(MESH_DIRECTORY / 'fort.14', crs=4326)
    print (mesh)
    fig,ax = plt.subplots(1,1,figsize=(10,10))
    ax = mesh.make_plot()
    ax.triplot(mesh.triangulation, color='k', linewidth=0.05)
    #ax.scatter(mesh.x[indexes], mesh.y[indexes], edgecolor='r', facecolor='none')
    plt.savefig('testmesh.png')
    plt.close()

The mesh.make_plot() line always gave me the following error,
ValueError: triangles max element is out of bounds

Please help.
Alex

**Comment by krober10nd** [comment]
How did you create the triangulation? Probably best to just use matplotlib for this

**Comment by shinbunya** [comment]
I've got the same error when I use plot_mesh command. Any suggestion?

```
(base) D:\work\adcirc-testsuite\adcirc\adcirc_shinnecock_inlet>plot_mesh fort.14 --crs EPSG:4326 --show-elements
D:\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Traceback (most recent call last):
  File "D:\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\Scripts\plot_mesh.exe\__main__.py", line 7, in <module>
  File "D:\anaconda3\lib\site-packages\adcircpy\cmd\plot_mesh.py", line 61, in main
    PlotMeshCommand(parse_args())
  File "D:\anaconda3\lib\site-packages\adcircpy\cmd\plot_mesh.py", line 16, in __init__
    mesh.make_plot(axes=ax, vmin=args.vmin, vmax=args.vmax)
  File "D:\anaconda3\lib\site-packages\adcircpy\figures.py", line 78, in decorator
    axes = f(*argv, **kwargs)
  File "D:\anaconda3\lib\site-packages\adcircpy\mesh\fort14.py", line 254, in make_plot
    self.tricontourf(axes=axes, levels=levels, vmin=vmin, vmax=vmax, **kwargs)
  File "D:\anaconda3\lib\site-packages\adcircpy\figures.py", line 78, in decorator
    axes = f(*argv, **kwargs)
  File "D:\anaconda3\lib\site-packages\adcircpy\mesh\base.py", line 463, in tricontourf
    ax = axes.tricontourf(self.x, self.y, self.triangles, self.values, **kwargs)
  File "D:\anaconda3\lib\site-packages\matplotlib\tri\tricontour.py", line 307, in tricontourf
    return TriContourSet(ax, *args, **kwargs)
    self.tricontourf(axes=axes, levels=levels, vmin=vmin, vmax=vmax, **kwargs)
  File "D:\anaconda3\lib\site-packages\adcircpy\figures.py", line 78, in decorator
    axes = f(*argv, **kwargs)
  File "D:\anaconda3\lib\site-packages\adcircpy\mesh\base.py", line 463, in tricontourf
    ax = axes.tricontourf(self.x, self.y, self.triangles, self.values, **kwargs)
  File "D:\anaconda3\lib\site-packages\matplotlib\tri\tricontour.py", line 307, in tricontourf
    return TriContourSet(ax, *args, **kwargs)
  File "D:\anaconda3\lib\site-packages\matplotlib\tri\tricontour.py", line 29, in __init__
    super().__init__(ax, *args, **kwargs)
  File "D:\anaconda3\lib\site-packages\matplotlib\contour.py", line 812, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\matplotlib\tri\tricontour.py", line 45, in _process_args
    tri, z = self._contour_args(args, kwargs)
  File "D:\anaconda3\lib\site-packages\matplotlib\tri\tricontour.py", line 58, in _contour_args
    tri, args, kwargs = Triangulation.get_from_args_and_kwargs(*args,
  File "D:\anaconda3\lib\site-packages\matplotlib\tri\triangulation.py", line 164, in get_from_args_and_kwargs
    triangulation = Triangulation(x, y, triangles, mask)
  File "D:\anaconda3\lib\site-packages\matplotlib\tri\triangulation.py", line 63, in __init__
    raise ValueError('triangles max element is out of bounds')
ValueError: triangles max element is out of bounds
```

**Comment by SorooshMani-NOAA** [comment]
@shinbunya, can you please test the latest [`bugfix/meshplot`](https://github.com/noaa-ocs-modeling/adcircpy/tree/bugfix/meshplot) branch? The issue with the triangle plots should be resolved in that branch. If everything looks good, I can merge it to `main` after review by other colleagues.
